version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
    depends_on:
      - db
    networks:
      - phpnet

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php_demo
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - phpnet

networks:
  phpnet:
